postgres_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DW_HOST') }}"
      user: "{{ env_var('DW_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_DW_PASSWORD') }}"
      port: "{{ env_var('DW_PORT') | int }}"
      dbname: "{{ env_var('DW_DB') }}"
      threads: 1
      connect_timeout: 30
      schema: public