data_source raw:
   type: postgres
   connection:
     host: ${POSTGRES_HOST}
     username: ${POSTGRES_USER}
     password: ${POSTGRES_PASSWORD}
   database: ${POSTGRES_DB}
   schema: raw

data_source retail:
   type: postgres
   connection:
     host: ${POSTGRES_HOST}
     username: ${POSTGRES_USER}
     password: ${POSTGRES_PASSWORD}
   database: ${POSTGRES_DB}
   schema: retail

soda_cloud:
  host: cloud.soda.io
  api_key_id: ${SODA_KEY}
  api_key_secret: ${SODA_KEY_SECRET}