data_source raw:
   type: postgres
   connection:
     host: ${DW_HOST}
     username: ${DW_USER}
     password: ${DW_PASSWORD}
   database: ${DW_DB}
   schema: raw

data_source retail:
   type: postgres
   connection:
     host: ${DW_HOST}
     username: ${DW_USER}
     password: ${DW_PASSWORD}
   database: ${DW_DB}
   schema: retail

soda_cloud:
  host: cloud.soda.io
  api_key_id: ${SODA_KEY}
  api_key_secret: ${SODA_KEY_SECRET}