services:
  postgres:
    image: postgres:15
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: metabaseappdb

  metabase:
    image: metabase/metabase:latest
    depends_on:
      - postgres
    expose:
      - "3001"
    ports:
      - "3000:3000"
    networks:
      - network
    environment:
      MB_DB_TYPE: postgres 
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres

volumes:
  postgres-volume:

networks:
  network: