version: 2

models:
  - name: dim_line
    columns:
      - name: line_id
        data_tests:
          - not_null
          - unique

  - name: dim_status
    columns:
      - name: status_severity
        data_tests:
          - not_null
          - unique
          - accepted_values:
              arguments:
                values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
                quote: false
      - name: status_category
        data_tests:
          - accepted_values:
              arguments:
                values: ['Good Service', 'Minor Delays', 'Reduced Service', 'Severe Delays', 'Part Closure', 'Planned Closure', 'Part Suspended', 'Suspended', 'Service Closed', 'Other']
      - name: severity_weight
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
                quote: false

  - name: dim_datetime
    columns:
      - name: date_key
        data_tests:
          - not_null
      - name: hour_of_day
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
                quote: false

  - name: fact_line_status_interval
    columns:
      - name: line_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_line')
                field: line_id
      - name: status_severity
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_status')
                field: status_severity
      - name: interval_start_ts
        data_tests:
          - not_null
      - name: interval_end_ts
        description: "Null for the current open interval; populated for closed historical intervals."
      - name: disruption_category
        data_tests:
          - accepted_values:
              arguments:
                values: ['Signal Failure', 'Train Cancellations', 'Customer Incident', 'Power Issue', 'Staffing', 'Weather', 'Engineering Work', 'Planned Closure', 'Unknown', 'Other']

  - name: fact_line_status_change
    columns:
      - name: line_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_line')
                field: line_id
      - name: new_status_severity
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_status')
                field: status_severity
      - name: prev_status_severity
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_status')
                field: status_severity

  - name: mart_line_hour
    columns:
      - name: line_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_line')
                field: line_id
      - name: bucket_hour
        data_tests:
          - not_null
      - name: service_date
        data_tests:
          - not_null
      - name: total_seconds
        data_tests:
          - not_null
      - name: good_service_seconds
        data_tests:
          - not_null
      - name: disruption_seconds
        data_tests:
          - not_null

  - name: mart_line_day
    columns:
      - name: line_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_line')
                field: line_id
      - name: service_date
        data_tests:
          - not_null
      - name: total_seconds
        data_tests:
          - not_null
      - name: good_service_seconds
        data_tests:
          - not_null
      - name: disruption_seconds
        data_tests:
          - not_null

  - name: current_line_status
    columns:
      - name: line_id
        data_tests:
          - not_null
          - unique
          - relationships:
              arguments:
                to: ref('dim_line')
                field: line_id
      - name: status_severity
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_status')
                field: status_severity
      - name: disruption_category
        data_tests:
          - accepted_values:
              arguments:
                values: ['Signal Failure', 'Train Cancellations', 'Customer Incident', 'Power Issue', 'Staffing', 'Weather', 'Engineering Work', 'Planned Closure', 'Unknown', 'Other']
